CapstoneProj3/Models/Syll.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CapstoneProj3.Models
{
    public class Syll
    {
        //public int Syllabus_ID { get; set; } = 0;
        //public int Course_ID { get; set; } = 0;
        //public int User_ID { get; set; } = 0;
        //public List<> Lr { get; set; }
        
        public List<Rubric> Lr { get; set; }
        public List<CourseOutcome> Lco { get; set; }
        //public DMISEntitiesxx db;

        //public string CO_Code { get; set; } = string.Empty;
        //public string CO_DESC { get; set; } = string.Empty;
        //public string CO_CVA { get; set; } = string.Empty;
        //public string CO_POactivated { get; set; } = string.Empty;
        //public string CO_DOLLevel { get; set; } = string.Empty;

        //public string Course_Name { get; set; } = string.Empty;
        //public string Course_Dept { get; set; } = string.Empty;
        //public int Course_Credit { get; set; } = 0;
        //public string Course_Equivalent { get; set; } = string.Empty;
        //public string Course_Pre_Req { get; set; } = string.Empty;
        //public string Course_Co_Req { get; set; } = string.Empty;
        //public string Course_Desc { get; set; } = string.Empty;

        public List<CourseDeliverableOutputsAndRequirement> Lcodor { get; set; }

        //public string OutputReq { get; set; } = string.Empty;
        //public string OutputReqDesc { get; set; } = string.Empty;
        //public string Cilo_Add { get; set; } = string.Empty;
        //public string ToA { get; set; } = string.Empty;

        public List<ClassroomAndLabPolicy> Lclp { get; set; }

        //public string CLP_desc { get; set; } = string.Empty;

        public List<LearningPlan> Llplan { get; set; }

        //public string LPlan_Outcome { get; set; } = string.Empty;
        //public int LPlan_No_hours { get; set; } = 0;
        //public string LPlan_Topics { get; set; } = string.Empty;
        //public int LPlan_TLA_ID { get; set; } = 0;
        //public string LPlan_Asses { get; set; } = string.Empty;

        public List<PEO> Lpeo { get; set; }

        //public string Peo_CODE { get; set; } = string.Empty;
        //public string Peo_DESC { get; set; } = string.Empty;
        //public string Peo_CVA { get; set; } = string.Empty;

        public List<ProgramOutcome> Lpo { get; set; }
      
        public int num { get; set; } = 0;
        public List<GradingSystem> Lgs { get; set; }
        //public string PO_Code { get; set; } = string.Empty;
        //public string PO_attr { get; set; } = string.Empty;
        //public string PO_Desc { get; set; } = string.Empty;
        //public string PO_CVA { get; set; } = string.Empty;



    }

}

CapstoneProj3/Controllers/SyllController.cs
using CapstoneProj3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapstoneProj3.Controllers
{
    public class SyllController : Controller
    {
        // GET: Syll
        DMISEntitiesxx db = new DMISEntitiesxx();
        public int logID=1;

        public ActionResult Index()
        {
            return View();
        }

        // GET: Syll/Details
        public ActionResult Details()
        {

            //var syll = new Models.Syll { Syllabus_ID = 123, Course_ID = 321, User_ID = 222 };
            AllSyllView all = new AllSyllView();
            List<Syll> butangView = new List<Syll>();
            
            List<Syllab> lsylstore = new List<Syllab>();
            List<Syllab> lsyl = new List<Syllab>();
            lsyl = db.Syllabs.ToList();
            foreach (var sud in lsyl)
            {
                if (sud.User_ID == this.logID)
                {
                    lsylstore.Add(sud);
                    
                }
            }

          
            List<CourseOutcome> Co = new List<CourseOutcome>();
            Co = db.CourseOutcomes.ToList();
            List<PEO> Peo = new List<PEO>();
            Peo = db.PEOs.ToList();
            List<ProgramOutcome> Po = new List<ProgramOutcome>();
            Po = db.ProgramOutcomes.ToList();
            List<ClassroomAndLabPolicy> Clp = new List<ClassroomAndLabPolicy>();
            Clp = db.ClassroomAndLabPolicies.ToList();
            List<CourseDeliverableOutputsAndRequirement> Codor = new List<CourseDeliverableOutputsAndRequirement>();
            Codor = db.CourseDeliverableOutputsAndRequirements.ToList();
            List<LearningPlan> Lp = new List<LearningPlan>();
            Lp = db.LearningPlans.ToList();
            List<GradingSystem> Gs = new List<GradingSystem>();
            Gs = db.GradingSystems.ToList();


            List<CourseOutcome> wCo = new List<CourseOutcome>();
            List<PEO> wPeo = new List<PEO>();
            List<ProgramOutcome> wPo = new List<ProgramOutcome>();
            List<ClassroomAndLabPolicy> wClp = new List<ClassroomAndLabPolicy>();
            List<CourseDeliverableOutputsAndRequirement> wCodor = new List<CourseDeliverableOutputsAndRequirement>();
            List<LearningPlan> wLp = new List<LearningPlan>();
            List<GradingSystem> wGs = new List<GradingSystem>();

            foreach (Syllab tanan in lsylstore)
            {
                Syll kuhaUsa = new Syll();
                
                foreach (var sud in Co)
                {
                    if (sud.Syllabus_ID == tanan.Syllabus_ID)
                    {
                        //CourseOutcome Coln = new CourseOutcome();
                        //kuhaUsa.Lco.Add(sud);
                        //Coln.Add(sud);
                        wCo.Add(sud);
                        
                       

                    }
                }
                foreach (var sud in Peo)
                {
                    if (sud.Syllabus_ID == tanan.Syllabus_ID)
                    {
                        //kuhaUsa.Lpeo.Add(sud);
                        wPeo.Add(sud);
                    }
                }
                foreach (var sud in Po)
                {
                    if (sud.Syllabus_ID == tanan.Syllabus_ID)
                    {
                        wPo.Add(sud);
                    }
                }
                foreach (var qwe in Clp)
                {
                    
                    if (qwe.Syllabus_ID == tanan.Syllabus_ID)
                    {

                        //kuhaUsa.Lclp.Add(qwe);
                        wClp.Add(qwe);
                      
                    }
                }
                foreach (var sud in Lp)
                {
                    if (sud.Syllabus_ID == tanan.Syllabus_ID)
                    {
                        //kuhaUsa.Llplan.Add(sud);
                        wLp.Add(sud);
                    }
                }
                foreach (var sud in Codor)
                {
                    if (sud.Syllabus_ID == tanan.Syllabus_ID)
                    {
                        wCodor.Add(sud);
                    }
                }
                foreach (var sud in Gs)
                {
                    if (sud.Syllabus_ID == tanan.Syllabus_ID)
                    {
                        wGs.Add(sud);
                    }
                }
                kuhaUsa.Lclp = wClp;
                kuhaUsa.Lco = wCo;
                kuhaUsa.Lcodor = wCodor;
                kuhaUsa.Lgs = wGs;
                kuhaUsa.Llplan = wLp;
                kuhaUsa.Lpeo = wPeo;
                kuhaUsa.Lpo = wPo;

                butangView.Add(kuhaUsa);
            }

            all.oru = butangView;
            return View(butangView);
        }

        // GET: Syll/Create
        public ActionResult Create()
        {
            Syll sy = new Syll();
            
            return View();
        }

        // POST: Syll/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Syll/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Syll/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Syll/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Syll/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [HttpPost]
        public ActionResult InsertSyll(Syll data)
        {
            List<Syllab> kita = new List<Syllab>();
            Syllab res = new Syllab();
            Syllab syllabus = new Syllab();


            

            syllabus.User_ID = logID;
            syllabus.Course_ID = 1;
            //IList<Syllab> syllablist = new List<Syllab>();
            db.Syllabs.Add(syllabus);

            
            kita=db.Syllabs.ToList();
            
            foreach(var sud in kita)
            {
                if (sud.Course_ID == syllabus.Course_ID)
                {
                    res = sud;
                    break;
                }
            }

            foreach (PEO p in data.Lpeo)
            {
                if (p.Peo_CODE !=null && p.Peo_CVA !=null  && p.Peo_DESC !=null) {
                    PEO peo = new PEO();
                    peo.Peo_CODE = p.Peo_CODE;
                    peo.Peo_DESC = p.Peo_DESC;
                    peo.Peo_CVA = p.Peo_CVA;
                    peo.Syllabus_ID = res.Syllabus_ID;

                    db.PEOs.Add(peo);

                    db.SaveChanges();
                }
            }

            foreach (ClassroomAndLabPolicy p in data.Lclp)
            {
                if (p.CLP_desc !=null) {
                    ClassroomAndLabPolicy classroomAndLabPolicies = new ClassroomAndLabPolicy();
                    classroomAndLabPolicies.CLP_desc = p.CLP_desc;
                    classroomAndLabPolicies.Syllabus_ID = res.Syllabus_ID;
                    db.ClassroomAndLabPolicies.Add(classroomAndLabPolicies);
                    db.SaveChanges();
                }
            }

            foreach (CourseDeliverableOutputsAndRequirement p in data.Lcodor)
            {
                if (p.OutputReq != null && p.OutputReqDesc != null && p.ToA!=null && p.Cilo_Add!=null) {
                    CourseDeliverableOutputsAndRequirement courseDeliverableOutputsAndRequirements = new CourseDeliverableOutputsAndRequirement();
                    courseDeliverableOutputsAndRequirements.OutputReq = p.OutputReq;
                    courseDeliverableOutputsAndRequirements.OutputReqDesc = p.OutputReqDesc;
                    courseDeliverableOutputsAndRequirements.Cilo_Add = p.Cilo_Add;
                    courseDeliverableOutputsAndRequirements.ToA = p.ToA;
                    courseDeliverableOutputsAndRequirements.Syllabus_ID = res.Syllabus_ID;
                    db.CourseDeliverableOutputsAndRequirements.Add(courseDeliverableOutputsAndRequirements);
                    db.SaveChanges();
                }
            }
            foreach (CourseOutcome p in data.Lco)
            {
                if (p.CO_Code != null && p.CO_CVA != null && p.CO_DESC != null && p.CO_DOLLevel != null & p.CO_POactivated != null) {
                    CourseOutcome courseOutcomes = new CourseOutcome();

                    courseOutcomes.CO_Code = p.CO_Code;
                    courseOutcomes.CO_DESC = p.CO_DESC;
                    courseOutcomes.CO_CVA = p.CO_CVA;
                    courseOutcomes.CO_POactivated = p.CO_POactivated;
                    courseOutcomes.CO_DOLLevel = p.CO_DOLLevel;
                    courseOutcomes.Syllabus_ID = res.Syllabus_ID;

                    db.CourseOutcomes.Add(courseOutcomes);

                    db.SaveChanges();
                }
            }
            foreach (GradingSystem p in data.Lgs)
            {
                if (p.GRD_outputs != null && p.GRD_type!= null && p.GRD_weight != null )
                {
                    GradingSystem gradingSystem = new GradingSystem();

CapstoneProj3/Views/Syll/Cr8CourseGet.cshtml
@model CapstoneProj3.Models.Course

@{
    ViewBag.Title = "Cr8CourseGet";
}

<h2>Cr8CourseGet</h2>


@using (Html.BeginForm("Cr8CoursePost","Syll",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.Course_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course_Dept, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course_Dept, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course_Dept, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course_Credit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course_Credit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course_Credit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course_Equivalent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course_Equivalent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course_Equivalent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course_Pre_Req, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course_Pre_Req, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course_Pre_Req, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course_Co_Req, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course_Co_Req, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course_Co_Req, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course_Desc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course_Desc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course_Desc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CapstoneProj3/Views/Syll/Details.cshtml
@using CapstoneProj3.Models
@model List<CapstoneProj3.Models.Syll>

@{
    ViewBag.Title = "Details";

}

<h2>Details</h2>

<div>
    <h4>Syll</h4>
    <hr />
    @foreach (var syl in Model)
    {

        <h2>ClassroomAndLabPolicies</h2>
        <table class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th class="text-center">Description</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var qwe in syl.Lclp)
                {
                    <tr>
                        <td><center>@qwe.CLP_desc</center> </td>
                    </tr>
                }
            </tbody>
        </table>
        <hr />
        <h2>Course Deliverable Outputs And Requirements</h2>
        <table class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th class="text-center">Output Requirement</th>
                    <th class="text-center">Output Requirement Description</th>
                    <th class="text-center">Cilo</th>
                    <th class="text-center">ToA</th>
                </tr>
            </thead>
            <tbody id="codor">
                @foreach (var qwe in syl.Lcodor)
                {
                    <tr>
                        <td><center>@qwe.OutputReq</center> </td>
                        <td><center>@qwe.OutputReqDesc</center> </td>
                        <td><center>@qwe.Cilo_Add</center> </td>
                        <td><center>@qwe.ToA</center> </td>
                    </tr>
                }
            </tbody>
        </table>
        <hr />
        <h2>Course Outcomes</h2>
        <table class="table table-hover table-bordered">

            <thead>

                <tr>
                    <th class="text-center">Code</th>
                    <th class="text-center">Description</th>
                    <th class="text-center">Core Value Activated</th>
                    <th class="text-center">PO Activated</th>
                    <th class="text-center">Domain of Level & Learning</th>
                </tr>
            </thead>
            <tbody id="butco">
                @foreach (var qwe in syl.Lco)
                {
                <tr>
                    <td><center>@qwe.CO_Code</center> </td>
                    <td><center>@qwe.CO_DESC</center> </td>
                    <td><center>@qwe.CO_CVA</center> </td>
                    <td><center>@qwe.CO_POactivated</center> </td>
                    <td><center>@qwe.CO_DOLLevel</center> </td>
                </tr>
                }
            </tbody>

        </table>
        <hr />


        <h2>Learning Plan</h2>
        <table class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th class="text-center">Outcome</th>
                    <th class="text-center">Number of Hours</th>
                    <th class="text-center">Topics</th>
                    <th class="text-center">Activity L</th>
                    <th class="text-center">Activity T</th>
                    <th class="text-center">Asses</th>
                </tr>
            </thead>
            <tbody id="lp">
                @foreach (var qwe in syl.Llplan)
                {
                    <tr>
                        <td><center>@qwe.LPlan_Outcome</center> </td>
                        <td><center>@qwe.LPlan_No_hours</center> </td>
                        <td><center>@qwe.LPlan_Topics</center> </td>
                        <td><center>@qwe.activityL</center> </td>
                        <td><center>@qwe.activityT</center> </td>
                    </tr>
                }
            </tbody>
        </table>
        <hr />
        <h2>Program Educational Objectives</h2>
        <table class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th class="text-center">Code</th>
                    <th class="text-center">Description</th>
                    <th class="text-center">Core Value Activated</th>
                </tr>
            </thead>
            <tbody id="peo">
                @foreach (var qwe in syl.Lpeo)
                {
                    <tr>
                        <td><center>@qwe.Peo_CODE</center> </td>
                        <td><center>@qwe.Peo_DESC</center> </td>
                        <td><center>@qwe.Peo_CVA</center> </td>
                    </tr>
                }
            </tbody>
        </table>
        <hr />
        <h2>Program Outcomes</h2>
        <table class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th class="text-center">Code</th>
                    <th class="text-center">Attribute</th>
                    <th class="text-center">Description</th>
                    <th class="text-center">Core Values ACtivated</th>
                </tr>
            </thead>
            <tbody id="po">
                @foreach (var qwe in syl.Lpo)
                {
                    <tr>
                        <td><center>@qwe.PO_Code</center> </td>
                        <td><center>@qwe.PO_attr</center> </td>
                        <td><center>@qwe.PO_Desc</center> </td>
                        <td><center>@qwe.PO_CVA</center> </td>
                    </tr>
                }
            </tbody>
        </table>
        <hr />
        <hr />
        <h2>Grading System</h2>
        <table class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th class="text-center">Outputs</th>
                    <th class="text-center">Type</th>
                    <th class="text-center">Weight</th>
                </tr>
            </thead>
            <tbody id="gs">
                @foreach (var qwe in syl.Lgs)
                {
                    <tr>
                        <td><center>@qwe.GRD_outputs</center> </td>
                        <td><center>@qwe.GRD_type</center> </td>
                        <td><center>@qwe.GRD_weight</center> </td>
                    </tr>
                }
            </tbody>
        </table>
        <hr />
        <br /><br /><br /><br /><br /><br /><br />
    
    }
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CapstoneProj3/Views/Syll/InsertSyll.cshtml
@model CapstoneProj3.Models.PEO

@{
    ViewBag.Title = "InsertSyll";
    
}

<h2>InsertSyll</h2>

<div>
    <h4>Syllab</h4>
    <hr />

    <table>
        <thead class="thead-dark">
            <tr>
                <th class="text-center"> Syllabus_ID</th>
                <th class="text-center">Course_ID</th>
                <th class="text-center">User_ID</th>
                
                <th class="text-center" colspan="2">Action</th>

            </tr>
        </thead>
        <tbody>
            
            
            <tr>
                <td>
                    
                </td>
                <td>
                    
                </td>
                <td>
                    
                </td>

            </tr>
            
        </tbody>
    </table>

</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CapstoneProj3/Views/Syll/login.cshtml
@model CapstoneProj3.Models.User

@{
    ViewBag.Title = "login";
}

<h2>login</h2>


@using (Html.BeginForm(Html.BeginForm("loginIn", "Syll", FormMethod.Post))) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Num, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ID_Num, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ID_Num, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CapstoneProj3/Views/Syll/loginIn.cshtml
@model CapstoneProj3.Models.User

@{
    ViewBag.Title = "loginIn";
}

<h2>loginIn</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ID_Num)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_Num)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cons_Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cons_Time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact_info)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact_info)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CapstoneProj3/Views/Syll/pickCourse.cshtml
@using CapstoneProj3.Models
@model CapstoneProj3.Models.DropDownCourse

@{
    ViewBag.Title = "pickCourse";
    
}

<h2>pickCourse</h2>


@using (Html.BeginForm("pickedCourse", "Syll", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Course</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    @{
        List<SelectListItem> listItems = new List<SelectListItem>();
        //for (var i = 0; i < 5; i++)
        foreach(var i in Model.lcr)
        {
            listItems.Add(new SelectListItem
            {
                Text = i.Course_Name,
                Value = ""+i.Course_ID
            });

        }
    }
    @{ Course c = new Course();}
    @Html.DropDownListFor(Model => Model.cr.Course_ID, listItems, "-- Select Status --")

    <input type="submit" value="SubmitCourse" />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CapstoneProj3/Views/Syll/pickedCourse.cshtml
@model CapstoneProj3.Models.Course

@{
    ViewBag.Title = "pickedCourse";
}

<h2>pickedCourse</h2>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_Dept)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_Dept)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_Credit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_Credit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_Equivalent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_Equivalent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_Pre_Req)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_Pre_Req)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_Co_Req)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_Co_Req)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_Desc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_Desc)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>